#=
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do
not exceed four million, find the sum of the even-valued terms.
=#

function fibonacci(n)
    #returns a fibonacci sequence up to the number n,
    f1, fn_1 = 0,0
    f2, fn = 1,1

    if n == 1
        fiblist = [f1]
    else n==2
        fiblist = [f1,f2]
    end

    if n>2
        while n >= fn+fn_1
            append!(fiblist, fn+fn_1)
            temp = fn
            fn = fn+fn_1
            fn_1 = temp
        end
    end
    return fiblist
end

fiblist = fibonacci(3999999)

evenfibs = []
for i in 1:length(fiblist)
    if iseven(fiblist[i])
        append!(evenfibs, fiblist[i])
    end
end

answer = sum(evenfibs)
